#spring:
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 500  #连接池的最大数据库连接数。设为0表示无限制
#        max-idle: 20   #最大空闲数
#        max-wait: -1
#        min-idle: 5
#    timeout: 1000