server:
  port: 8091
service:
  version: 1.0.0
dubbo:
  scan:
    base-packages: top.b0x0.cloud.alibaba.provider.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
#    rest:
#      name: rest
#      port: 9090
#      server: netty
feign:
  hystrix:
    enabled: true