#spring:
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 500  #连接池的最大数据库连接数。设为0表示无限制
#        max-idle: 20   #最大空闲数
#        max-wait: -1
#        min-idle: 5
#    timeout: 1000

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.105.146.74:3306/ac_mall_cloud_order_service_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =GMT%2B8
#    username: order_service_u
#    password: order_service_PWD_123
#
#    #hikari数据库连接池
#    hikari:
#      pool-name: YH_HikariCP
#      minimum-idle: 10 #最小空闲连接数量
#      idle-timeout: 600000 #空闲连接存活最大时间，默认600000（10分钟）
#      maximum-pool-size: 100 #连接池最大连接数，默认是10
#      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
#      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
#      connection-test-query: SELECT 1

