dubbo:
  cloud:
    subscribed-services: alibaba-rpc-sample-client,alibaba-rpc-sample-provide2
  #    subscribed-services: ${spring.application.name}
  scan:
    base-packages: top.b0x0.cloud.alibaba.provide.service
  #  protocols:
  #    dubbo:
  #      port: -1
  protocol:
    name: dubbo #dubbo 协议
    port: -1  #dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
  consumer:
    check: false

spring:
  application:
    name: alibaba-rpc-sample-provide
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 7776